name: 'ga4_attribution'
version: '1.0.0'

profile: 'ga4_attribution'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ga4_attribution:
    01_staging:
      +materialized: view
      +schema: staging
    02_activity:
      +materialized: view
      +schema: activity
    03_identity:
      +materialized: table
      +schema: identity
    04_attribution:
      +materialized: table
      +schema: attribution
    05_analytics:
      +materialized: table
      +schema: analytics
